<head>
<title>Cadastro de Empresas</title>
</head>


    <h2>Cadastro de Empresas - Todos os cadastros</h2>
<p class="text-right"> <a class="btn btn-primary" href="<?=$this->url(array("controller"=>"empresa","action"=>"new"),null,true)?>">Cadastrar Empresa</a></p>

<table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
      <th>CNPJ</th>
      <th>Nome</th>
      <th>Ações</th>
   </tr>
   <?foreach($this->dados AS $key => $empresa):?>
   <tr>
      <td><?=$empresa['cnpj']?></td>
      <td><?=$empresa['nome']?></td>
      <td>
         <a href="<?=$this->url(array("controller"=>"empresa","action"=>"show","id"=>"{$empresa['id']}"),null,true)?>"><button class="btn btn-primary">Visualizar<i class="icon-eye-open"></i></button> </a>
         <a href="<?=$this->url(array("controller"=>"empresa","action"=>"edit","id"=>"{$empresa['id']}"),null,true)?>"><button class="btn btn-primary"> Editar<i class="icon-pencil"></button></i></a>
         <a href="<?=$this->url(array("controller"=>"empresa","action"=>"destroy","id"=>"{$empresa['id']}"),null,true)?>"><button class="btn btn-primary"> Excluir<i class="icon-trash"></button></i></a>
      </td>
   </tr>
   <?endforeach;?>
</table>