<h2>Cadastro de Empresas - Adicionar Cadastro</h2>
<form action="<?=$this->url(array("controller"=>"empresa","action"=>"create"),null,true)?>" method="post">
   <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="2">
      <tr>
         <td>Nome:</td>
         <td><input type="text" name="nome" value="" /></td>
      </tr>
      <tr>
         <td>CNPJ:</td>
         <td><input type="text" name="cnpj" value="" /></td>
      </tr>
      <tr>
         <td>Responsavel:</td>
         <td><input type="text" name="responsavel" value="" /></td>
      </tr>
      <tr>
         <td>Email do responsavel:</td>
         <td><input type="text" name="email_responsavel" value="" /></td>
      </tr>
      <tr>
         <td>Telefone do responsavel:</td>
         <td><input type="text" name="tel_responsavel" value="" /></td>
      </tr>
      <tr>
         <td>Data de alteracao:</td>
         <td><input type="text" name="dt_alteracao" value="" /></td>
      </tr>
   </table>
   <input type="submit" value="Enviar" />
</form>