<h2>Cadastro de Empresas - Visualizar Cadastro</h2>
<form action="<?=$this->url(array("controller"=>"empresa","action"=>"create"),null,true)?>" method="post">
   <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="2">
      <tr>
         <td>Nome:</td>
         <td><input type="text" name="nome" value="<?php echo $this->empresa['nome']?>" autocomplete="off" readonly/></td>
      </tr>
      <tr>
         <td>CNPJ:</td>
         <td><input type="text" name="cnpj" value="<?php echo $this->empresa['cnpj']?>" autocomplete="off" readonly /></td>
      </tr>
      <tr>
         <td>Responsavel:</td>
         <td><input type="text" name="responsavel" value="<?php echo $this->empresa['responsavel']?>" autocomplete="off" readonly /></td>
      </tr>
      <tr>
         <td>Email do responsavel:</td>
         <td><input type="email" name="email_responsavel" value="<?php echo $this->empresa['email_responsavel']?>" autocomplete="off" readonly /></td>
      </tr>
      <tr>
         <td>Telefone do responsavel:</td>
         <td><input type="tel" name="tel_responsavel" value="<?php echo $this->empresa['tel_responsavel']?>" autocomplete="off" readonly /></td>
      </tr>
   </table>
   <button type="submit" class="btn btn-primary">Enviar<i class="icon-ok"></i></button>
   <a href="<?=$this->url(array("controller"=>"empresa","action"=>"edit","id"=>"{$empresa['id']}"),null,true)?>"><button class="btn btn-primary"> Editar<i class="icon-pencil"></button></i></a>
   <a href="<?=$this->url(array("controller"=>"empresa","action"=>"destroy","id"=>"{$empresa['id']}"),null,true)?>"><button class="btn btn-primary"> Excluir<i class="icon-trash"></button></i></a>
</form>